# #################################
# Parameters of the final model
#
# Authors:
#  * Heitor Guimarães 2022
# #################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

sample_rate: 16000

# Set up folders for reading from and writing to
exp_name: exp_meetup_itau
data_folder: ../dataset
output_folder: !ref ../logs/<exp_name>
model_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
audio_result: !ref <output_folder>/audio_results

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json

train_folder: !ref <data_folder>/se_itau_train
valid_folder: !ref <data_folder>/se_itau_dev

# logs with training statistics
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: !ref <train_log>

# Training Parameters
train_sampling: True
max_train_sample_size: 80000    # Maximum number of samples to use during train
number_of_epochs: 50
batch_size: 8

train_dataloader_options:
    batch_size: !ref <batch_size>

valid_dataloader_options:
    batch_size: !ref <batch_size> 
